Overboard fixes
towards-a-new-leftypol/leftypol_lainchan pull request #112
Opened 2021-01-09 07:28 UTC by nonmakina

Removes the random capability from the overboard and fixes the thread preview generator.
It used to show posts that were in the middle of the thread, now it shows the last posts.

2021-01-09 23:22 UTC, nonmakina commented
Overboard has link to catalog, but the link is broken.

2021-01-10 00:52 UTC, nonmakina commented
Overboard link thing has a problem.

2021-01-10 01:49 UTC, nonmakina commented
Possibly related to the relative filepath issue. 
https://github.com/towards-a-new-leftypol/leftypol_lainchan/issues/124

2021-01-11 12:05 UTC, towards-a-new-leftypol requested changes
Overall really great, we just need to fix the DRY principle violation.

2021-01-11 12:05 UTC, towards-a-new-leftypol commented on templates/themes/semirand/theme.php
> +			$replies = $this->fetchReplies($post['board'], $post['id'], $preview_count);
:+1:

2021-01-11 12:05 UTC, towards-a-new-leftypol commented on inc/display.php
> +    if (isset($config['prepended_foreign_boards'])){
You shouldn't copy paste this block, please refactor this out to it's own function.

2021-01-11 12:08 UTC, towards-a-new-leftypol commented on inc/instance-config.php
> +    'overboard' => '/overboard',
missing a trailing slash (link at the top on dev does not work without this)

2021-01-11 16:38 UTC, towards-a-new-leftypol submitted a review, later dismissed

2021-01-11 16:44 UTC, towards-a-new-leftypol approved these changes

2021-01-11 16:54 UTC, merged